### ISSUE TITLE
/articles: glossary word popover often missing image

### ISSUE THREAD

**Issue by bryceerobertson** [StampyAI/stampy-ui#488] opened 2024-03-06 13:05 UTC
![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/5a8f588c-5ca5-4c87-9876-fdaf5266554b)

I think it would be a worthwhile improvement to ensure all definitions have an image. It helps maintain attention and therefore engagement.

**Comment by ricewithabee** [comment] 2024-03-06 13:05
I'm happy to go through finding/creating images for this if that helps.

**Comment by mruwnik** [comment] 2024-03-06 17:53
They're pulled from this document: https://docs.google.com/document/d/1Rm7tN5zTErZq0E4qqAZoNVzClS94Kb_rQOLaViu2p6c/edit if you want to add any

**Comment by LeMurphant** [comment] 2024-03-07 05:18
Procedure to generate them and discussion can be found here
https://discord.com/channels/677546901339504640/1209317607073775716

**Comment by melissasamworth** [comment] 2024-03-08 04:46
Yep agreed!

**Comment by LeMurphant** [comment] 2024-09-25 16:47
I would argue this is not a bug, but an ongoing TODO item. Even then with https://github.com/StampyAI/stampy-ui/issues/674 in mind, I'm not sure this is even something we want to do. I will close it, feel free to re-open if you disagree.

**Closed** 2024-11-04 17:09 UTC
Labels: bug
