### ISSUE TITLE
Feature Request: Thumbs down button

### ISSUE THREAD

**Issue by markovial** [StampyAI/stampy-ui#289] opened 2023-07-29 09:25 UTC
Would allow for better understanding of which answers need extra attention in particular.

On click the button should probably prompt for a comment by the user on how exactly the answer was unhelpful, and then remind them that they can also go into google docs to leave more granular comments about specific parts of the text if they so wish.

**Comment by Aprillion** [comment] 2023-07-29 10:16
Duplicate of #83 => let's close this one and move discussion there.

**Closed by Aprillion** 2023-07-29 10:16 UTC
