### ISSUE TITLE
search articles input shouldn't be highlighted by default

### ISSUE THREAD

**Issue by melissasamworth** [StampyAI/stampy-ui#545] opened 2024-03-09 00:33 UTC
Images in advanced section still broken

![Image](https://github.com/StampyAI/stampy-ui/assets/825910/4b6d49df-30d8-404d-83e7-0a53d72a2d07)

**Comment by LeMurphant** [comment] 2024-03-20 05:37
duplicate of https://github.com/StampyAI/stampy-ui/issues/544 and/or https://github.com/StampyAI/stampy-ui/issues/547

**Closed** 2024-03-20 05:37 UTC
