### ISSUE TITLE
Feature request: More search results on nlp.stampy.ai

### ISSUE THREAD

**Issue by srkaas** [StampyAI/stampy-ui#350] opened 2023-12-01 06:42 UTC
Someone using nlp.stampy.ai while helping with the distillation fellowship said it would be more useful if it showed more results than 5 at the same time (maybe with radio buttons to select the number of results), like 20 or 100 or something.

**Comment by ccstan99** [comment] 2023-12-01 07:03
This is a duplicate of https://github.com/StampyAI/stampy-nlp/issues/31 which is in the repo where the code needs to be changed. I'm going to close this one.

**Closed by ccstan99** 2023-12-01 07:03 UTC
